cc_library(
    name = "NCursesLib",
    srcs = ["ncurses_wrapper.cc"],
    hdrs = ["ncurses_wrapper.h"],
    visibility = ["//visibility:public"],
    deps = ["@ncurses//:main"]
)

cc_library(
    name = "SolutionLib",
    srcs = ["solution.cc"],
    hdrs = ["solution.h"],
    visibility = ["//visibility:public"],
)
